### ISSUE TITLE
Certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by urihersh** [hllhll/HomeAssistant-EKON-iAircon#14]
The home assistant log is full of repetitive error messages:
```
2020-09-13 23:00:17 ERROR (Thread-228) [custom_components.ekon.climate] ws_on_error() - WS Error:
2020-09-13 23:00:17 ERROR (Thread-228) [custom_components.ekon.climate] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
```
The problem starts after updating to the latest version, I suspect this commit -m b122768499479817f56e7933d1b8af378b613538
I restored to the first commit before it and the error was gone.

The configuration is very simple:
```
climate:
- platform: ekon
  name: Main account
  username: !secret tadiran_user
  password: !secret tadiran_password
  base_url: https://www.airconet.xyz/
```

**Platform:**
 - OS: Raspbian
 - Version: Home Assistant 0.114.4
