### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by yosiyaffe** [hllhll/HomeAssistant-EKON-iAircon#6]
**Describe the bug**
using the latest ekon version + HA 0.111.4

**To Reproduce**
on load in log will show 

Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 12:27:21 AM (3 occurrences)
Last logged: 12:27:22 AM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ekon doing I/O at custom_components/ekon/climate.py, line 219: result = self._http_session.post(url, params=url_params, data="")
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ekon doing I/O at custom_components/ekon/climate.py, line 200: result = self._http_session.get(url)

**Configuration**
```yaml
- platform: ekon
  name: "Main account"
  username: "xxxxxxx"
  password: "xxxxxxx"
  base_url: https://www.airconet.xyz/
``` 

**Platform:**
 - OS: ubuntu 20.04 ,HA docker 0.111.4
 - Browser chrome latest
 - Version [e.g. 0.92.1]
