### ISSUE TITLE
state history not updating

### ISSUE THREAD

**Issue by icherfas** [hllhll/HomeAssistant-EKON-iAircon#8]
**Describe the bug**
state history of the entity not getting updated

**To Reproduce**
at first the integration stopped working with this error:
`Failed to call service climate/set_hvac_mode. HTTPSConnectionPool(host='www.airconet.xyz', port=443): Max retries exceeded with url: /dev/switchHvac/5CCF7F4F46FB?on=False (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xa9315c90>: Failed to establish a new connection: [Errno 22] Invalid argument'))`
after reboot hassio the integration started to work but the history is not updating (I have tried to reboot a couple of times)

**Configuration**
```
climate:
- platform: ekon
  # This currently unused:
  name: Main account
  # Specify the name and password for your account
  username: **********@gmail.com
  password: *********
  # This specifies the server that the component would work with, I have only tried it with EKON server (Airconet APP)
  # Optional, defults to Airconet server
  # Use this if you are using "Airconet" app - EKON main server
  base_url: https://www.airconet.xyz/
  name_mapping:
  - id : ****
    name: Living_Room_AC
```

**Expected behavior**
I would expect for the history to work :)
**Screenshots**

![image](https://user-images.githubusercontent.com/48028629/88661272-eb784180-d0e0-11ea-8f3a-44c8ad465fbf.png)

**Platform:**
 - OS: home assistant OS on RPI4
 - Browser chrome/android app
 - Version 0.112.4

**Additional context**
from the logfile:
```
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 12:30:34 PM (1 occurrences)
Last logged: 12:30:34 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for ekon doing I/O at custom_components/ekon/climate.py, line 318: result = self._http_session.get(url)
```
